### ISSUE TITLE
Would like add ServiceMonitor template option on the helm chart

### ISSUE THREAD

**Issue by konvergence** [draganm/missing-container-metrics#22]
Hello Draganm,

Thanks a lot for for project.
I did'nt find the github source of your helm chart.

Is it possible to add optional serviceMonitor section that will allow to generate ?
- service
- servicemonitor

example

```
  serviceMonitor:
    enabled: true
    port: 3001
    scrapeInterval: 15s
```
